spring:
  datasource:
    username: root
    password: Root@2022
    url: jdbc:mysql://121.37.194.21:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

